---
- hosts: mariadbs
  become: yes

  tasks:
  - name: Install Utility software
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - software-properties-common
      - apache2
      - git
